### ISSUE TITLE
Able to run it without Google

### ISSUE THREAD

**Issue by TheNeikos** [AelitaBot/aelita#127]
If I wanted to run this without relying on Google how would I set this software up?

**Comment by notriddle** [comment]
$ cargo build --release
    $ ./target/release/aelita config.toml

Should work.

**Comment by TheNeikos** [comment]
It does launch, but then it just hangs there.
I must have done something wrong, here are my steps:

1. clone & build
2. Create a bot account
3. On the bot account get a user token (with `repo` access) and put it into the config
4. On the bot account create an oauth app
5. Copy the client token from the oauth app
6. change projects table to  `projects."furry.cafe"` as that is the name of my repo as well (but on my account, not the bots)

Anything here sound wrong?

I get an empty page when trying to access the app on its port, is that expected? Same thing for the github-callback (I did expect an error here)

**Comment by notriddle** [comment]
Did it print something out like "Created {} pipelines, {} CIs, {} UIs, and {} VCSs (View: {})"

You don't need oAuth unless you're either trying to set up the whole GUI frontend, like aelitabot.xyz has, or you want to put the queue viewer behind an authentication wall. You need to set up webhooks, though, so you'd set stuff up like this:

```toml
[config.view]
listen = "localhost:8000"
secret = "YOU CAN MAKE THIS UP; IT DOESN'T COME FROM GITHUB"

[config.github]
listen = "localhost:6000"
user = "THE BOT'S USER"
owner = "TheNeikos"
token = "THE PERSONAL ACCESS TOKEN"
secret = "THE WEBHOOK SECRET; YOU ACTUALLY MAKE THIS UP, TOO"
git = {}

[config.jenkins]
# https://wiki.jenkins-ci.org/display/JENKINS/Notification+Plugin
listen = "localhost:7000"
host = "http://MY_JENKINS_HOST"
user = "MY_JENKINS_USER"
token = "MY_JENKINS_API_TOKEN"

[projects."furry.cafe"]
github = {}
jenkins = { token = "MY_BUILD_TOKEN" }
```
